import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation — Navbar keys
    navHome: 'Home',
    navAbout: 'About Us',
    navSupport: 'Support',
    navContact: 'Contact',
    navLogin: 'Login',
    navSignUp: 'Sign Up',
    navLogout: 'Logout',

    // Welcome Page badges & updated terminology
    heroBadge: 'Industrial Diagnostic Platform',
    heroTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    heroSubheading: 'Condition monitoring and leak detection for turbocharged diesel engines using industrial diagnostics.',
    heroDesc: 'Monitor engine condition, detect intake and exhaust air leaks, and receive maintenance assessment reports.',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    featuresTitle: 'System Capabilities',
    feature1Title: 'Condition Monitoring',
    feature1Desc: 'Continuous evaluation of engine operating parameters for intake and exhaust air system integrity.',
    feature2Title: 'Leak Detection System',
    feature2Desc: 'Classification of intake, exhaust, or combined leakage conditions based on sensor data analysis.',
    feature3Title: 'Maintenance Assessment',
    feature3Desc: 'GO / NON-GO diagnostic output with confidence score and actionable maintenance recommendations.',

    // About page
    aboutBadge: 'About This Platform',
    aboutUs: 'About Us',
    aboutUsSubtitle: 'Intake and Exhaust Air Leak Detection — Industrial Diagnostic Platform.',
    objectivesTitle: 'Project Objectives',
    objectivesContent: [
      'Detect intake air leaks in turbocharged diesel engines',
      'Detect exhaust air leaks and manifold failures',
      'Reduce unplanned maintenance and equipment downtime',
      'Support maintenance teams with condition-based assessment',
      'Generate structured diagnostic reports for field engineers',
    ],

    // Login Page
    loginTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    loginSubtitle: 'Industrial Engine Diagnostics System',
    operatorLogin: 'Operator Login',
    adminLogin: 'Administrator Login',
    loginType: 'Login Type',
    username: 'Username',
    employeeId: 'Employee ID',
    password: 'Password',
    rememberMe: 'Remember Me',
    forgotPassword: 'Forgot Password?',
    signUp: 'Sign Up',
    dontHaveAccount: "Don't have an account?",
    loginBtn: 'Authenticate & Access',
    authenticating: 'Authenticating User...',
    verifying: 'Verifying Credentials...',
    loadingSystem: 'Loading Industrial Monitoring Platform...',
    secureSession: 'Simulated 256-Bit Encrypted Session',

    // Registration Page
    registerTitle: 'Create Enterprise Account',
    registerSubtitle: 'Register new maintenance or operations staff',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    email: 'Email Address',
    mobileNumber: 'Mobile Number',
    orgInfo: 'Organization Details',
    catBranch: 'Caterpillar Branch',
    department: 'Department',
    userRole: 'User Role',
    securityInfo: 'Security Details',
    confirmPassword: 'Confirm Password',
    passwordStrength: 'Password Strength',
    weak: 'Weak',
    medium: 'Medium',
    strong: 'Strong',
    passwordMismatch: 'Passwords do not match',
    registerBtn: 'Submit Credentials',
    verificationTitle: 'Security Verification Required',
    otpSent: 'A verification code has been simulated for testing.',
    enterOtp: 'Enter 6-Digit OTP',
    verifyBtn: 'Verify & Register',
    encrypting: 'Simulating Cryptographic Hash Storage (bcrypt)...',
    secureSuccess: 'User registered in mock database.',

    // Dashboard Page
    dashboardTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    welcomeBack: 'Welcome Back',
    currentSession: 'Active Diagnostics Session',
    engineStatus: 'Engine Status',
    systemStatus: 'System Status',
    analysisHistory: 'Analysis History',
    lastPrediction: 'Last Prediction',
    activeEngine: '3512C HD Engine Active',
    operational: 'All Sensors Online',
    runsAnalyzed: 'Tests Run',
    noLeaksFound: 'No Leaks Classified Yet',
    startAnalysis: 'Start AI Diagnostics',
    resetInputs: 'Reset Parameters',
    engineInputs: 'Engine Inputs',
    intakeSensors: 'Intake Sensors',
    exhaustSensors: 'Exhaust Sensors',
    fuelInjectionTime: 'Fuel Injection Time (ms)',
    rpm: 'Engine RPM',
    fuelRate: 'Fuel Rate (kg/h)',
    injectionPressure: 'Fuel Injection Pressure (bar)',
    maf: 'MAF Sensor (kg/h)',
    map: 'MAP Sensor (bar)',
    mat: 'MAT Sensor (°C)',
    deltaP: 'Delta Pressure Sensor (mbar)',
    turboInletP: 'Turbo Inlet Pressure (bar)',
    turbineInletP: 'Turbine Inlet Pressure (bar)',
    egt: 'EGT Sensor (°C)',
    nox: 'NOx Sensor (ppm)',
    invalidInputs: 'Please enter valid values for all sensor parameters.',

    // Analysis Page
    analysingTitle: 'AI Analysis In Progress',
    step1: 'Collecting Sensor Data...',
    step2: 'Validating Parameters...',
    step3: 'Running AI Leak Detection Model...',
    step4: 'Generating Confidence Score...',
    step5: 'Preparing Recommendations...',
    estTime: 'Estimated Time: 5 Seconds',

    // Results Page
    resultsTitle: 'Diagnostics Analysis Output',
    status: 'System Status',
    classification: 'Leak Classification',
    confidenceScore: 'Confidence Score',
    riskLevel: 'Risk Level',
    noLeak: 'No Leak Detected',
    intakeLeak: 'Intake Manifold Leak',
    exhaustLeak: 'Exhaust System Leak',
    combinedLeak: 'Intake + Exhaust Leakage',
    go: 'GO (SYSTEM CLEAR)',
    nongo: 'NON-GO (MAINTENANCE REQUIRED)',
    low: 'Low Risk',
    riskMedium: 'Medium Risk',
    high: 'High Risk',
    critical: 'Critical Alert',
    recommendations: 'Maintenance Instructions',
    recInspectManifold: 'Inspect the intake manifold seals and visual check for micro-cracks.',
    recCheckHose: 'Examine turbocharger inlet/outlet flexible hoses for signs of fatigue or loose hose clamps.',
    recVerifyPiping: 'Verify charge air intercooler piping connections and conduct pressure drop test.',
    recInspectExhaust: 'Inspect the exhaust manifold gaskets and weld joints for carbon soot deposits.',
    recPressureTest: 'Perform high-pressure smoke test to precisely locate micro-leaks.',

    // Report Page
    reportTitle: 'Engine Diagnostic Report',
    downloadPdf: 'Download PDF Report',
    printReport: 'Print Hard Copy',
    newAnalysis: 'Run New Test',
    technicianSig: 'Technician Signature',
    supervisorSig: 'Supervisor Signature',
    dateOfAnalysis: 'Analysis Timestamp',
    systemDiagnosticLog: 'INTAKE AND EXHAUST AIR LEAK DETECTION — Diagnostic Log Sheet',

    // Support page — new keys
    supportBadge: 'Technical Support Center',
    supportTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    supportSubtitle: 'Technical documentation, troubleshooting, and support resources.',
    userGuideTitle: 'User Guide',
    userGuideText: 'This platform supports condition monitoring and leak detection for Caterpillar turbocharged diesel engines. Select your engine model, enter operating parameters, and run the diagnostic analysis to receive a GO or NON-GO assessment.',
    guideStep1Title: 'Select Engine & Enter Parameters',
    guideStep1Desc: 'Choose C7 or C15 engine model and enter RPM, fuel rate, injection time and pressure.',
    guideStep2Title: 'Run Diagnostic Analysis',
    guideStep2Desc: 'The system evaluates parameters and classifies intake or exhaust leak conditions.',
    guideStep3Title: 'Review Results & Download Report',
    guideStep3Desc: 'View GO/NON-GO result, confidence score, leak location, and maintenance actions. Generate PDF report.',
    sysReqTitle: 'System Requirements',
    sysReqBrowser: 'Browser',
    sysReqOS: 'Operating System',
    sysReqRAM: 'Memory',
    sysReqNetwork: 'Network',
    sysReqResolution: 'Display',
    raiseTicketTitle: 'Contact Technical Support',
    raiseTicketDesc: 'If you are experiencing issues with the diagnostic system, raise a support ticket and a technical representative will assist you.',
    thIssue: 'Issue',
    thCause: 'Probable Cause',
    thAction: 'Corrective Action',
    errC004Issue: 'CAN Bus Connection Timeout',
    errC004Cause: 'OBD-II hardware diagnostics coupler interface disconnected.',
    errC004Action: 'Check physical cable connector lock and verify engine battery voltage > 24V.',
    errS912Issue: 'EGT Sensor Reading Out of Bounds',
    errS912Cause: 'Exhaust thermocouple adapter has high resistance or broken wiring.',
    errS912Action: 'Perform multimeter impedance check on pins, replace EGT probe if > 2.5 ohms.',
    errP015Issue: 'MAP Sensor Inconsistent Pressure Drop',
    errP015Cause: 'Intake charge air coupler blocked or hose disconnected.',
    errP015Action: 'Inspect intercooler intake plumbing and re-torque clamp brackets.',

    // Contact Page
    contactTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    contactSubtitle: 'Get in touch with global technical teams',
    name: 'Full Name',
    message: 'Message Detail',
    sendMessage: 'Submit Form',
    formSubmitted: 'Your support ticket has been simulated and printed to terminal.',
    phone: 'Main Support Line',
    office: 'Technical HQ',
    supportEmail: 'Diagnostics Email',

    // About Us Carousel
    aboutUs: 'About Us',
    aboutUsSubtitle: 'Learn more about our Intake and Exhaust Air Leak Detection Platform.',
    projectOverview: 'Project Overview',
    projectOverviewContent: 'The Intake and Exhaust Air Leak Detection platform identifies air leakage conditions in turbocharged diesel engines and provides maintenance teams with structured diagnostic output including GO/NON-GO assessment and service recommendations.',
    problemStatement: 'Problem Statement',
    problemStatementContent: 'Undetected intake and exhaust air leaks reduce engine efficiency, increase fuel consumption, impair turbocharger performance, raise emissions, and cause unexpected equipment downtime.',
    ourSolution: 'Our Solution',
    ourSolutionContent: 'The system evaluates engine operating parameters and delivers a GO or NON-GO assessment, confidence score, and maintenance recommendations to support structured maintenance decisions.',
    keyFeatures: 'Key Features',
    keyFeaturesContent: ['Intake & Exhaust Leak Detection', 'Confidence Score Output', 'Maintenance Recommendations', 'GO / NON-GO Assessment', 'Multi-Language Support', 'PDF Diagnostic Report Generation'],
    applications: 'Applications',
    applicationsContent: ['Heavy-Duty Construction Equipment', 'Mining Machinery', 'Industrial Diesel Engines', 'Commercial Heavy Vehicles', 'Fleet Maintenance Operations'],
    ourGoal: 'Our Goal',
    ourGoalContent: 'To support operators, technicians, and maintenance engineers in identifying intake and exhaust air leak conditions efficiently, improving equipment reliability and reducing unplanned downtime.',
    slideCounter: 'of'
  },
  ta: {
    // Navigation
    home: 'முகப்பு',
    leakDetection: 'கசிவு கண்டறிதல்',
    diagnostics: 'கண்டறிதல்',
    reports: 'அறிக்கைகள்',
    support: 'ஆதரவு',
    contact: 'தொடர்பு',
    login: 'உள்நுழை',
    logout: 'வெளியேறு',
    admin: 'நிர்வாகி',
    operator: 'இயக்குபவர்',
    engineer: 'பொறியாளர்',
    supervisor: 'மேற்பார்வையாளர்',

    // Welcome Page
    heroTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    heroSubheading: 'மெஷின் லேர்னிங் மற்றும் தொழில்துறை கண்டறிதல்களைப் பயன்படுத்தி நிகழ்நேர உறிஞ்சுதல் மற்றும் வெளியேற்ற கசிவைக் கண்டறிதல்.',
    heroDesc: 'என்ஜின் ஆரோக்கியத்தை கண்காணிக்கவும், செயலிழப்புகளை கணிக்கவும், கசிவுகளை கண்டறியவும் மற்றும் பராமரிப்பு பரிந்துரைகளை பெறவும்.',
    getStarted: 'தொடங்குங்கள்',
    learnMore: 'மேலும் அறிய',
    featuresTitle: 'அமைப்பின் திறன்கள்',
    feature1Title: 'நிகழ்நேர டெலிமெட்ரி',
    feature1Desc: '12 தனித்துவமான என்ஜின் மற்றும் வெளியேற்ற சென்சார் அளவுருக்களின் தொடர்ச்சியான வாசிப்பு.',
    feature2Title: 'முன்கணிப்பு AI மாதிரி',
    feature2Desc: 'உறிஞ்சுதல், வெளியேற்றம் அல்லது ஒருங்கிணைந்த கசிவு புள்ளிகளை அடையாளம் காணும் மேம்பட்ட வகைப்பாடு.',
    feature3Title: 'கேட்டர்பில்லர் தொழில்துறை வடிவமைப்பு',
    feature3Desc: 'தொழில்நுட்ப சவால்களுக்காக பிரத்யேகமாக வடிவமைக்கப்பட்ட உயர்தர தொழில்துறை இடைமுகம்.',

    // Login Page
    loginTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    loginSubtitle: 'Industrial Engine Diagnostics System',
    operatorLogin: 'இயக்குபவர் உள்நுழைவு',
    adminLogin: 'நிர்வாகி உள்நுழைவு',
    loginType: 'உள்நுழைவு வகை',
    username: 'பயனர் பெயர்',
    employeeId: 'பணியாளர் ஐடி',
    password: 'கடவுச்சொல்',
    rememberMe: 'என்னை நினைவில் கொள்',
    forgotPassword: 'கடவுச்சொல்லை மறந்தீர்களா?',
    signUp: 'பதிவு செய்',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    loginBtn: 'அங்கீகரித்து அணுகவும்',
    authenticating: 'பயனர் அங்கீகரிக்கப்படுகிறார்...',
    verifying: 'சான்றுகள் சரிபார்க்கப்படுகின்றன...',
    loadingSystem: 'தொழில்துறை கண்காணிப்பு தளம் ஏற்றப்படுகிறது...',
    secureSession: 'பாதுகாப்பான 256-பிட் குறியாக்கப்பட்ட அமர்வு',

    // Registration Page
    registerTitle: 'நிறுவன கணக்கை உருவாக்கவும்',
    registerSubtitle: 'புதிய பராமரிப்பு அல்லது செயல்பாட்டு பணியாளர்களை பதிவு செய்யவும்',
    personalInfo: 'தனிப்பட்ட தகவல்',
    fullName: 'முழு பெயர்',
    email: 'மின்னஞ்சல் முகவரி',
    mobileNumber: 'கைபேசி எண்',
    orgInfo: 'நிறுவன விவரங்கள்',
    catBranch: 'கேட்டர்பில்லர் கிளை',
    department: 'துறை',
    userRole: 'பயனர் பங்கு',
    securityInfo: 'பாதுகாப்பு விவரங்கள்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    passwordStrength: 'கடவுச்சொல் வலிமை',
    weak: 'பலவீனமானது',
    medium: 'நடுத்தரம்',
    strong: 'வலிமையானது',
    passwordMismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
    registerBtn: 'சான்றுகளைச் சமர்ப்பிக்கவும்',
    verificationTitle: 'பாதுகாப்பு சரிபார்ப்பு தேவை',
    otpSent: 'சோதனைக்காக ஒரு சரிபார்ப்புக் குறியீடு உருவகப்படுத்தப்பட்டுள்ளது.',
    enterOtp: '6-இலக்க OTP ஐ உள்ளிடவும்',
    verifyBtn: 'சரிபார்த்து பதிவு செய்யவும்',
    encrypting: 'மறைக்குறியீட்டு ஹாஷ் சேமிப்பு உருவகப்படுத்தப்படுகிறது (bcrypt)...',
    secureSuccess: 'பயனர் உருவகப்படுத்தப்பட்ட தரவுத்தளத்தில் பதிவு செய்யப்பட்டுள்ளார்.',

    // Dashboard Page
    dashboardTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    welcomeBack: 'மீண்டும் வருக',
    currentSession: 'செயலில் உள்ள கண்டறியும் அமர்வு',
    engineStatus: 'என்ஜின் நிலை',
    systemStatus: 'அமைப்பு நிலை',
    analysisHistory: 'பகுப்பாய்வு வரலாறு',
    lastPrediction: 'கடைசி கணிப்பு',
    activeEngine: '3512C HD என்ஜின் செயலில் உள்ளது',
    operational: 'அனைத்து சென்சார்களும் ஆன்லைனில் உள்ளன',
    runsAnalyzed: 'இயக்கப்பட்ட சோதனைகள்',
    noLeaksFound: 'இன்னும் கசிவுகள் கண்டறியப்படவில்லை',
    startAnalysis: 'AI பகுப்பாய்வைத் தொடங்கு',
    resetInputs: 'அளவுருக்களை மீட்டமை',
    engineInputs: 'என்ஜின் உள்ளீடுகள்',
    intakeSensors: 'உறிஞ்சும் சென்சார்கள் (Intake)',
    exhaustSensors: 'வெளியேற்றும் சென்சார்கள் (Exhaust)',
    fuelInjectionTime: 'எரிபொருள் ஊசி நேரம் (ms)',
    rpm: 'என்ஜின் RPM',
    fuelRate: 'எரிபொருள் விகிதம் (kg/h)',
    injectionPressure: 'எரிபொருள் ஊசி அழுத்தம் (bar)',
    maf: 'MAF சென்சார் (kg/h)',
    map: 'MAP சென்சார் (bar)',
    mat: 'MAT சென்சார் (°C)',
    deltaP: 'டெல்டா அழுத்த சென்சார் (mbar)',
    turboInletP: 'டர்போ நுழைவு அழுத்தம் (bar)',
    turbineInletP: 'டர்பைன் நுழைவு அழுத்தம் (bar)',
    egt: 'EGT சென்சார் (°C)',
    nox: 'NOx சென்சார் (ppm)',
    invalidInputs: 'அனைத்து சென்சார் அளவுருக்களுக்கும் செல்லுபடியாகும் மதிப்புகளை உள்ளிடவும்.',

    // Analysis Page
    analysingTitle: 'AI பகுப்பாய்வு செயல்பாட்டில் உள்ளது',
    step1: 'சென்சார் தரவைச் சேகரிக்கிறது...',
    step2: 'அளவுருக்களைச் சரிபார்க்கிறது...',
    step3: 'AI கசிவு கண்டறியும் மாதிரியை இயக்குகிறது...',
    step4: 'நம்பிக்கை மதிப்பெண்ணை உருவாக்குகிறது...',
    step5: 'பரிந்துரைகளைத் தயாரிக்கிறது...',
    estTime: 'மதிப்பிடப்பட்ட நேரம்: 5 வினாடிகள்',

    // Results Page
    resultsTitle: 'கண்டறியும் பகுப்பாய்வு வெளியீடு',
    status: 'அமைப்பின் நிலை',
    classification: 'கசிவு வகைப்பாடு',
    confidenceScore: 'நம்பிக்கை மதிப்பெண்',
    riskLevel: 'ஆபத்து நிலை',
    noLeak: 'கசிவு கண்டறியப்படவில்லை',
    intakeLeak: 'உறிஞ்சும் பன்மடி கசிவு (Intake Leak)',
    exhaustLeak: 'வெளியேற்ற அமைப்பு கசிவு (Exhaust Leak)',
    combinedLeak: 'உறிஞ்சுதல் + வெளியேற்ற கசிவு',
    go: 'GO (அமைப்பு தெளிவானது)',
    nongo: 'NON-GO (பராமரிப்பு தேவை)',
    low: 'குறைந்த ஆபத்து',
    riskMedium: 'நடுத்தர ஆபத்து',
    high: 'அதிக ஆபத்து',
    critical: 'முக்கியமான எச்சரிக்கை',
    recommendations: 'பராமரிப்பு வழிமுறைகள்',
    recInspectManifold: 'உறிஞ்சும் பன்மடி முத்திரைகளை ஆய்வு செய்து, விரிசல்கள் இருக்கிறதா என சரிபார்க்கவும்.',
    recCheckHose: 'டர்போசார்ஜர் குழாய்களில் தளர்வு அல்லது சேதம் இருக்கிறதா என சரிபார்க்கவும்.',
    recVerifyPiping: 'சார்ஜ் ஏர் இண்டர்கூலர் குழாய் இணைப்புகளை சரிபார்த்து அழுத்த சோதனையை நடத்தவும்.',
    recInspectExhaust: 'கார்பன் படிவுகள் உள்ளதா என வெளியேற்ற பன்மடி கேஸ்கெட்டுகளை ஆய்வு செய்யவும்.',
    recPressureTest: 'நுண் கசிவுகளை துல்லியமாக கண்டறிய உயர் அழுத்த புகை சோதனையை செய்யவும்.',

    // Report Page
    reportTitle: 'என்ஜின் கண்டறியும் அறிக்கை',
    downloadPdf: 'PDF அறிக்கையைப் பதிவிறக்கு',
    printReport: 'அறிக்கையை அச்சிடு',
    newAnalysis: 'புதிய சோதனை செய்',
    technicianSig: 'தொழில்நுட்ப வல்லுநர் கையொப்பம்',
    supervisorSig: 'மேற்பார்வையாளர் கையொப்பம்',
    dateOfAnalysis: 'பகுப்பாய்வு நேரம்',
    systemDiagnosticLog: 'INTAKE AND EXHAUST AIR LEAK DETECTION — Diagnostic Log Sheet',

    // Support Page
    supportTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    userManual: 'பயனர் கையேடு & வழிகாட்டிகள்',
    howToUse: 'கணினியை எவ்வாறு இயக்குவது',
    howToUseText: 'உங்கள் கேட்டர்பில்லர் கண்காணிப்பு முனையத்திலிருந்து டெலிமெட்ரி மதிப்புகளை உள்ளிட்டு, AI பகுப்பாய்வை இயக்க "AI பகுப்பாய்வைத் தொடங்கு" என்பதை அழுத்தவும்.',
    faqs: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    faq1: 'AI கண்டறிதல் மாதிரி எவ்வளவு துல்லியமானது?',
    faq1Ans: 'துல்லியமான அளவுருக்கள் வழங்கப்படும்போது ஆழமான கற்றல் மாதிரி 94.7% துல்லியத்தை அடைகிறது.',
    faq2: 'GO மற்றும் NON-GO இடையே உள்ள வேறுபாடு என்ன?',
    faq2Ans: 'GO என்பது என்ஜின் பாதுகாப்பான வரம்பில் இயங்குவதைக் குறிக்கிறது. NON-GO என்பது உடனடி பராமரிப்பு தேவைப்படுவதைக் குறிக்கிறது.',
    faq3: 'இதை நேரடி என்ஜினுடன் இணைக்க முடியுமா?',
    faq3Ans: 'ஆம், இந்த மென்பொருள் பிளாஸ்க் ஏபிஐ (Flask API) உடன் எளிதாக ஒருங்கிணைக்கும் வகையில் வடிவமைக்கப்பட்டுள்ளது.',
    troubleshooting: 'கணினி பிழைகளைத் தீர்ப்பது',
    errorTitle: 'கண்டறியும் பிழை தீர்வு',
    contactSupportBtn: 'அவசர ஆதரவு டிக்கெட்டைத் திற',

    // Contact Page
    contactTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    contactSubtitle: 'உலகளாவிய தொழில்நுட்பக் குழுக்களுடன் தொடர்பு கொள்ளுங்கள்',
    name: 'முழு பெயர்',
    message: 'செய்தி விவரம்',
    sendMessage: 'படிவத்தைச் சமர்ப்பி',
    formSubmitted: 'உங்கள் ஆதரவு டிக்கெட் வெற்றிகரமாக உருவகப்படுத்தப்பட்டது.',
    phone: 'முதன்மை ஆதரவு லைன்',
    office: 'தொழில்நுட்ப தலைமையகம்',
    supportEmail: 'கண்டறியும் மின்னஞ்சல்',

    // About Us Carousel
    aboutUs: 'எங்களைப் பற்றி',
    aboutUsSubtitle: 'எங்கள் உறிஞ்சுதல் மற்றும் வெளியேற்ற காற்று கசிவு கண்டறிதல் தளத்தைப் பற்றி மேலும் அறியுங்கள்.',
    projectOverview: 'திட்ட மேலோட்டம்',
    projectOverviewContent: 'உறிஞ்சுதல் மற்றும் வெளியேற்ற காற்று கசிவு கண்டறிதல் தளம் டர்போசார்ஜ் செய்யப்பட்ட டீசல் என்ஜின்களில் சாத்தியமான காற்று கசிவு நிலைமைகளை அடையாளம் காணவும், நுண்ணறிவுமிக்க கண்டறியும் நுண்ணறிவுகளுடன் பராமரிப்பு குழுக்களை ஆதரிக்கவும் வடிவமைக்கப்பட்டுள்ளது.',
    problemStatement: 'பிரச்சனை அறிக்கை',
    problemStatementContent: 'கண்டறியப்படாத உறிஞ்சுதல் மற்றும் வெளியேற்ற காற்று கசிவுகள் என்ஜின் செயல்திறனைக் குறைக்கலாம், எரிபொருள் நுகர்வு அதிகரிக்கலாம், டர்போசார்ஜர் செயல்திறனை பாதிக்கலாம், உமிழ்வுகளை அதிகரிக்கலாம், மற்றும் எதிர்பாராத செயல்நிறுத்தத்திற்கு வழிவகுக்கலாம்.',
    ourSolution: 'எங்கள் தீர்வு',
    ourSolutionContent: 'இந்த அமைப்பு என்ஜின் செயல்பாட்டு அளவுருக்களை பகுப்பாய்வு செய்து GO அல்லது NON-GO மதிப்பீடு, நம்பிக்கை மதிப்பெண் மற்றும் தகவலறிந்த பராமரிப்பு முடிவுகளை ஆதரிக்க பராமரிப்பு பரிந்துரைகளை வழங்குகிறது.',
    keyFeatures: 'முக்கிய அம்சங்கள்',
    keyFeaturesContent: ['கசிவு கண்டறிதல் ஆதரவு', 'நம்பிக்கை மதிப்பெண்', 'ஸ்மார்ட் பரிந்துரைகள்', 'பயனர் நட்பு டாஷ்போர்டு', 'பல மொழி ஆதரவு', 'இருண்ட மற்றும் ஒளி பயன்முறை'],
    applications: 'பயன்பாடுகள்',
    applicationsContent: ['கனரக லாரிகள்', 'சுரங்க உபகரணங்கள்', 'கட்டுமான இயந்திரங்கள்', 'தொழில்துறை டீசல் என்ஜின்கள்', 'கடற்படை பராமரிப்பு நடவடிக்கைகள்'],
    ourGoal: 'எங்கள் இலக்கு',
    ourGoalContent: 'நுண்ணறிவுமிக்க கசிவு கண்டறிதலின் மூலம் உபகரண நம்பகத்தன்மையை மேம்படுத்துவது, பராமரிப்பு செலவுகளைக் குறைப்பது, செயல்நிறுத்தத்தைக் குறைப்பது மற்றும் திறமையான செயல்பாட்டை ஆதரிப்பது.',
    slideCounter: 'இல்'
  },
  hi: {
    // Navigation
    home: 'होम',
    leakDetection: 'लीक डिटेक्शन',
    diagnostics: 'डायग्नोस्टिक्स',
    reports: 'रिपोर्ट्स',
    support: 'सपोर्ट',
    contact: 'संपर्क',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    admin: 'प्रशासक',
    operator: 'ऑपरेटर',
    engineer: 'इंजीनियर',
    supervisor: 'पर्यवेक्षक',

    // Welcome Page
    heroTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    heroSubheading: 'मशीन लर्निंग और औद्योगिक निदान का उपयोग करके वास्तविक समय में सेवन और निकास रिसाव का पता लगाना।',
    heroDesc: 'इंजन स्वास्थ्य की निगरानी करें, विफलताओं की भविष्यवाणी करें, लीक का पता लगाएं, और रखरखाव की सिफारिशें प्राप्त करें।',
    getStarted: 'शुरू करें',
    learnMore: 'और जानें',
    featuresTitle: 'प्रणाली की क्षमताएं',
    feature1Title: 'वास्तविक समय टेलीमेट्री',
    feature1Desc: '12 अलग-अलग इंजन और निकास सेंसर मापदंडों की निरंतर निगरानी।',
    feature2Title: 'भविष्य कहनेवाला एआई मॉडल',
    feature2Desc: 'सेवन (Intake), निकास (Exhaust) या संयुक्त रिसाव बिंदुओं की पहचान करने वाला उन्नत वर्गीकरण।',
    feature3Title: 'कैटरपिलर औद्योगिक डिजाइन',
    feature3Desc: 'विशेष रूप से तकनीकी चुनौती संचालन के लिए स्टाइल किया गया मजबूत औद्योगिक इंटरफ़ेस।',

    // Login Page
    loginTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    loginSubtitle: 'Industrial Engine Diagnostics System',
    operatorLogin: 'ऑपरेटर लॉगिन',
    adminLogin: 'प्रशासक लॉगिन',
    loginType: 'लॉगिन प्रकार',
    username: 'उपयोगकर्ता नाम',
    employeeId: 'कर्मचारी आईडी',
    password: 'पासवर्ड',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    signUp: 'साइन अप करें',
    dontHaveAccount: 'खाता नहीं है?',
    loginBtn: 'सत्यापित करें और प्रवेश करें',
    authenticating: 'उपयोगकर्ता को प्रमाणित किया जा रहा है...',
    verifying: 'साख का सत्यापन किया जा रहा है...',
    loadingSystem: 'औद्योगिक निगरानी मंच लोड हो रहा है...',
    secureSession: 'सुरक्षित 256-बिट एन्क्रिप्टेड सत्र',

    // Registration Page
    registerTitle: 'एंटरप्राइज खाता बनाएं',
    registerSubtitle: 'नए रखरखाव या संचालन कर्मचारियों को पंजीकृत करें',
    personalInfo: 'व्यक्तिगत जानकारी',
    fullName: 'पूरा नाम',
    email: 'ईमेल पता',
    mobileNumber: 'मोबाइल नंबर',
    orgInfo: 'संगठन विवरण',
    catBranch: 'कैटरपिलर शाखा',
    department: 'विभाग',
    userRole: 'उपयोगकर्ता भूमिका',
    securityInfo: 'सुरक्षा विवरण',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    passwordStrength: 'पासवर्ड की ताकत',
    weak: 'कमजोर',
    medium: 'मध्यम',
    strong: 'मजबूत',
    passwordMismatch: 'पासवर्ड मेल नहीं खाते',
    registerBtn: 'साख सबमिट करें',
    verificationTitle: 'सुरक्षा सत्यापन आवश्यक',
    otpSent: 'परीक्षण के लिए एक सत्यापन कोड सिम्युलेट किया गया है।',
    enterOtp: '6-अंकीय OTP दर्ज करें',
    verifyBtn: 'सत्यापित करें और पंजीकृत करें',
    encrypting: 'क्रिप्टोग्राफिक हैश स्टोरेज सिम्युलेट किया जा रहा है (bcrypt)...',
    secureSuccess: 'उपयोगकर्ता सिम्युलेटेड डेटाबेस में पंजीकृत हो गया है।',

    // Dashboard Page
    dashboardTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    welcomeBack: 'स्वागत है',
    currentSession: 'सक्रिय डायग्नोस्टिक सत्र',
    engineStatus: 'इंजन की स्थिति',
    systemStatus: 'सिस्टम की स्थिति',
    analysisHistory: 'विश्लेषण इतिहास',
    lastPrediction: 'अंतिम भविष्यवाणी',
    activeEngine: '3512C HD इंजन सक्रिय है',
    operational: 'सभी सेंसर ऑनलाइन हैं',
    runsAnalyzed: 'परीक्षण किए गए',
    noLeaksFound: 'अभी तक कोई रिसाव नहीं मिला है',
    startAnalysis: 'AI विश्लेषण शुरू करें',
    resetInputs: 'पैरामीटर्स रीसेट करें',
    engineInputs: 'इंजन इनपुट',
    intakeSensors: 'इंटेक सेंसर (Intake)',
    exhaustSensors: 'एग्जॉस्ट सेंसर (Exhaust)',
    fuelInjectionTime: 'ईंधन इंजेक्शन समय (ms)',
    rpm: 'इंजन RPM',
    fuelRate: 'ईंधन दर (kg/h)',
    injectionPressure: 'ईंधन इंजेक्शन दबाव (bar)',
    maf: 'MAF सेंसर (kg/h)',
    map: 'MAP सेंसर (bar)',
    mat: 'MAT सेंसर (°C)',
    deltaP: 'डेल्टा दबाव सेंसर (mbar)',
    turboInletP: 'टर्बो इनलेट दबाव (bar)',
    turbineInletP: 'टर्बाइन इनलेट दबाव (bar)',
    egt: 'EGT सेंसर (°C)',
    nox: 'NOx सेंसर (ppm)',
    invalidInputs: 'कृपया सभी सेंसर मापदंडों के लिए मान्य मान दर्ज करें।',

    // Analysis Page
    analysingTitle: 'एआई विश्लेषण चल रहा है',
    step1: 'सेंसर डेटा एकत्र किया जा रहा है...',
    step2: 'मापदंडों का सत्यापन किया जा रहा है...',
    step3: 'एआई रिसाव पहचान मॉडल चलाया जा रहा है...',
    step4: 'विश्वसनीयता स्कोर तैयार किया जा रहा है...',
    step5: 'सिफारिशें तैयार की जा रही हैं...',
    estTime: 'अनुमानित समय: 5 सेकंड',

    // Results Page
    resultsTitle: 'डायग्नोस्टिक्स विश्लेषण आउटपुट',
    status: 'सिस्टम स्थिति',
    classification: 'रिसाव वर्गीकरण',
    confidenceScore: 'विश्वसनीयता स्कोर',
    riskLevel: 'जोखिम स्तर',
    noLeak: 'कोई रिसाव नहीं मिला',
    intakeLeak: 'इंटेक मैनिफोल्ड रिसाव',
    exhaustLeak: 'एग्जॉस्ट सिस्टम रिसाव',
    combinedLeak: 'इंटेक + एग्जॉस्ट रिसाव',
    go: 'GO (सिस्टम स्पष्ट है)',
    nongo: 'NON-GO (रखरखाव आवश्यक)',
    low: 'कम जोखिम',
    riskMedium: 'मध्यम जोखिम',
    high: 'उच्च जोखिम',
    critical: 'गंभीर चेतावनी',
    recommendations: 'रखरखाव के निर्देश',
    recInspectManifold: 'इंटेक मैनिफोल्ड सील का निरीक्षण करें और माइक्रो-क्रैक की जांच करें।',
    recCheckHose: 'टर्बोचार्जर होज़ के ढीले होने या खराब होने की जाँच करें।',
    recVerifyPiping: 'चार्ज एयर इंटरकूलर पाइपिंग कनेक्शनों को सत्यापित करें और दबाव परीक्षण करें।',
    recInspectExhaust: 'कार्बन जमा के लिए एग्जॉस्ट मैनिफोल्ड गास्केट का निरीक्षण करें।',
    recPressureTest: 'सूक्ष्म रिसाव का सटीक पता लगाने के लिए उच्च दबाव धूम्रपान परीक्षण करें।',

    // Report Page
    reportTitle: 'इंजन डायग्नोस्टिक रिपोर्ट',
    downloadPdf: 'PDF रिपोर्ट डाउनलोड करें',
    printReport: 'रिपोर्ट प्रिंट करें',
    newAnalysis: 'नया परीक्षण करें',
    technicianSig: 'तकनीशियन हस्ताक्षर',
    supervisorSig: 'पर्यवेक्षक हस्ताक्षर',
    dateOfAnalysis: 'विश्लेषण का समय',
    systemDiagnosticLog: 'INTAKE AND EXHAUST AIR LEAK DETECTION — Diagnostic Log Sheet',

    // Support Page
    supportTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    userManual: 'उपयोगकर्ता मैनुअल और गाइड',
    howToUse: 'सिस्टम का संचालन कैसे करें',
    howToUseText: 'अपने कैटरपिलर मॉनिटरिंग टर्मिनल से टेलीमेट्री मान दर्ज करें और विश्लेषण चलाने के लिए "AI विश्लेषण शुरू करें" दबाएं।',
    faqs: 'अक्सर पूछे जाने वाले प्रश्न',
    faq1: 'AI डिटेक्शन मॉडल कितना सटीक है?',
    faq1Ans: 'सटीक मापदंड प्रदान किए जाने पर मॉडल 94.7% सटीकता प्राप्त करता है।',
    faq2: 'GO और NON-GO में क्या अंतर है?',
    faq2Ans: 'GO का मतलब है इंजन सुरक्षित सीमा में चल रहा है। NON-GO इंगित करता है कि तत्काल मरम्मत की आवश्यकता है।',
    faq3: 'क्या मैं इसे लाइव इंजन के साथ जोड़ सकता हूँ?',
    faq3Ans: 'हां, इस सॉफ़्टवेयर को फ्लास्क एपीआई (Flask API) के साथ एकीकृत करने के लिए डिज़ाइन किया गया है।',
    troubleshooting: 'सिस्टम त्रुटियों का निवारण',
    errorTitle: 'डायग्नोस्टिक त्रुटि समाधान',
    contactSupportBtn: 'आपातकालीन टिकट खोलें',

    // Contact Page
    contactTitle: 'INTAKE AND EXHAUST AIR LEAK DETECTION',
    contactSubtitle: 'वैश्विक तकनीकी टीमों के संपर्क में रहें',
    name: 'पूरा नाम',
    message: 'संदेश विवरण',
    sendMessage: 'फ़ॉर्म सबमिट करें',
    formSubmitted: 'आपका सपोर्ट टिकट सफलतापूर्वक सिम्युलेट किया गया है।',
    phone: 'मुख्य सपोर्ट लाइन',
    office: 'तकनीकी मुख्यालय',
    supportEmail: 'डायग्नोस्टिक्स ईमेल',

    // About Us Carousel
    aboutUs: 'हमारे बारे में',
    aboutUsSubtitle: 'हमारे इंटेक और एग्जॉस्ट एयर लीक डिटेक्शन प्लेटफॉर्म के बारे में और जानें।',
    projectOverview: 'परियोजना अवलोकन',
    projectOverviewContent: 'इंटेक और एग्जॉस्ट एयर लीक डिटेक्शन प्लेटफॉर्म टर्बोचार्ज्ड डीजल इंजनों में संभावित वायु रिसाव स्थितियों की पहचान करने और रखरखाव टीमों को बुद्धिमान निदान अंतर्दृष्टि के साथ समर्थन प्रदान करने के लिए डिज़ाइन किया गया है।',
    problemStatement: 'समस्या कथन',
    problemStatementContent: 'अनडिटेक्टेड इंटेक और एग्जॉस्ट एयर लीक इंजन की दक्षता को कम कर सकते हैं, ईंधन की खपत बढ़ा सकते हैं, टर्बोचार्जर के प्रदर्शन को प्रभावित कर सकते हैं, उत्सर्जन बढ़ा सकते हैं, और अप्रत्याशित डाउनटाइम का कारण बन सकते हैं।',
    ourSolution: 'हमारा समाधान',
    ourSolutionContent: 'सिस्टम इंजन ऑपरेटिंग पैरामीटर का विश्लेषण करता है और सूचित रखरखाव निर्णयों का समर्थन करने के लिए GO या NON-GO मूल्यांकन, विश्वास स्कोर, और रखरखाव सिफारिशें प्रदान करता है।',
    keyFeatures: 'मुख्य विशेषताएं',
    keyFeaturesContent: ['लीक डिटेक्शन सपोर्ट', 'कॉन्फिडेंस स्कोर', 'स्मार्ट सिफारिशें', 'उपयोगकर्ता-अनुकूल डैशबोर्ड', 'बहुभाषी समर्थन', 'डार्क और लाइट मोड'],
    applications: 'अनुप्रयोग',
    applicationsContent: ['हेवी ट्रक', 'माइनिंग इक्विपमेंट', 'कंस्ट्रक्शन मशीनरी', 'औद्योगिक डीजल इंजन', 'फ्लीट मेंटेनेंस ऑपरेशन्स'],
    ourGoal: 'हमारा लक्ष्य',
    ourGoalContent: 'बुद्धिमान लीक डिटेक्शन के माध्यम से उपकरण विश्वसनीयता में सुधार, रखरखाव लागत को कम करना, डाउनटाइम को न्यूनतम करना, और कुशल संचालन का समर्थन करना।',
    slideCounter: 'का'
  }
};

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState(() => {
    return localStorage.getItem('cat-locale') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('cat-locale', locale);
  }, [locale]);

  const t = (key) => {
    return translations[locale]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
